name: marketimers-tv-api
services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: https://github.com/k00baPriv/digital_ocean_app_David
  name: marketimers-tv-api
